#!/bin/bash
#rm -f datasets/grid*


GRAPH_SIZE=784
TRAINSAMPLES=10
VALIDSAMPLES=10
TESTSAMPLES=10

#rm -f results/loss_${TRAINSAMPLES}*

#python ./datasets/dataset_gen_grid.py $HEIGHT $WIDTH $TRAINSAMPLES $VALIDSAMPLES $TESTSAMPLES
#DATASET="datasets/grid_${HEIGHT}x${WIDTH}_${TRAINSAMPLES}${VALIDSAMPLES}${TESTSAMPLES}.npz"
KERAS_BACKEND=tensorflow

ORIG_PATH="./results/loss_${TRAINSAMPLES}${VALIDSAMPLES}${TESTSAMPLES}_orig.txt"
python mnist_tester.py $GRAPH_SIZE $TRAINSAMPLES $VALIDSAMPLES $TESTSAMPLES orig > $ORIG_PATH
PROPOSED_PATH="./results/loss_${TRAINSAMPLES}${VALIDSAMPLES}${TESTSAMPLES}_proposed.txt"
python mnist_tester.py $GRAPH_SIZE $TRAINSAMPLES $VALIDSAMPLES $TESTSAMPLES minus > $PROPOSED_PATH

